print("hello,name---> i am 13 yrs old")
print("hellow world--->adam is black")
print("hello----> alhayat school grade 7 ")
print("adam")
print("ahmad")
print("yasir")
print("yathreb")
print("hello")
print("shalom")